### ISSUE TITLE
Show number of stashes (if >0)

### ISSUE THREAD

**Issue by apinkney97** [banga/powerline-shell#114]
I have a bad habit of stashing and then forgetting about it. It would be useful if the git segment displayed the number of stashes (if any exist).

The number of stashes can be obtained with (eg) 'git stash list | wc -l'.

**Comment by vitriol** [comment]
Has the stash segment been added anywhere? I want to use this lib, but not without the stash segment. I couldnt find any in the segments folder.

**Comment by apinkney97** [comment]
Hi! (Apologies for taking 4 months to respond...)

I never got round to doing this anywhere else other than uncommitted in my own local copy, as I was under the impression I was the only person interested.

I'm happy to tidy it up and submit a pull request though -- hopefully I'll do it this evening.

**Comment by b-ryan** [comment]
Based on discussion and age of this issue, I'm going to close this. I'm happy to look at a PR for a separate segment, but I do not plan to implement one myself.
