### ISSUE TITLE
Stuck in command history

### ISSUE THREAD

**Issue by LeonardoGentile** [banga/powerline-shell#135]
If I browse the latest used commands with the arrow keys everything works as it should. But if I am on any item of the history, let's say for example `python hello.py` and if I move the cursor of just one position either to the right or to the left (meaning on the `y` letter or a space further the end of the line) I get stuck and I can't scroll the history up or down anymore. I actually can't do anything but hit `return` key to execute the command I am stuck in or press `ctrl + u` to erase the current content of the command line I'm stuck in.

**Comment by b-ryan** [comment]
@LeonardoGentile can you confirm whether or not this is still an issue?

**Comment by LeonardoGentile** [comment]
yes, it is still an issue for me

**Comment by pradyunsg** [comment]
@LeonardoGentile Try running a prestine shell, i.e. without anything loaded through .bashrc (or whichever shell config you use). Do that by commenting out the entire file. If the issue still exists, try to figure out what lines are causing the issue and please tell us what you find.

**Comment by b-ryan** [comment]
@pradyunsg left a helpful comment. Unfortunately I don't have a mac to test using iterm2. I just don't think I'm going to be able to help here and I don't think there have been any other reports of it happening. Seems like it might be specific to your setup. Let me know if there's some way I can be helpful though.
