### ISSUE TITLE
Adding Solarized theme

### ISSUE THREAD

**Issue by ruturajv** [banga/powerline-shell#142]
Adding solarized light theme and tweaking the dark one.

![solarized-dark](https://cloud.githubusercontent.com/assets/227817/2926463/e1f5e772-d75c-11e3-9ed7-97480c3c919c.png)
![solarized-light](https://cloud.githubusercontent.com/assets/227817/2926464/e1f69140-d75c-11e3-8b92-094540bfffe6.png)

Check ruturajv@d5e202b124fc20fec6a2503faf9ab995f4a6f92b

**Comment by JohannesMattsson** [comment]
When I set  THEME = "solarized-dark" in config.py it looks like this:
![image](https://cloud.githubusercontent.com/assets/8685472/13001227/ec6e5c5e-d163-11e5-8c05-2e285adf0e22.png)

Any ideas what I am doing wrong?
