### ISSUE TITLE
Does it work under Cygwin?

### ISSUE THREAD

**Issue by metyl** [banga/powerline-shell#163]
Any comments are welcome.

**Comment by lucas59356** [comment]
It worked for me but the special characters don't work
![2016-10-26_17-05-18](https://cloud.githubusercontent.com/assets/15693688/19741170/6d7b5aea-9b9e-11e6-8919-1e71440c1e85.jpg)

**Comment by mikepruett3** [comment]
It does work under Cygwin. Need to install the [Powerline Fonts](https://github.com/Lokaltog/powerline-fonts) for it to look perfect. I used "Source Code Pro Light" for this shot.

![image](https://cloud.githubusercontent.com/assets/5198641/21826406/ef813c00-d74c-11e6-8151-286623fe5e52.png)

**Comment by b-ryan** [comment]
Looks like this got resolved. Note you can also use the [`--mode`](https://github.com/banga/powerline-shell#all-shells) option if you cannot get the fonts working.
