### ISSUE TITLE
Icons not working properly

### ISSUE THREAD

**Issue by phanib** [banga/powerline-shell#219]
Showing ? (Question marks)

<img width="574" alt="screen shot 2015-12-19 at 12 57 26 pm" src="https://cloud.githubusercontent.com/assets/3476532/11914831/17d0f300-a650-11e5-91ff-9dda5bb9b8d7.png">

Any idea?

**Comment by Junus** [comment]
I also have this issue

**Comment by ryanoasis** [comment]
Was the problem unpatched fonts?

**Comment by b-ryan** [comment]
@phanib have you followed the instructions in the README about patching your fonts? https://github.com/milkbikis/powerline-shell#setup

**Comment by Junus** [comment]
@ryanoasis I just set `Meslo` font to iTerm

**Comment by andrewdmcleod** [comment]
Was having the same problem - question marks. I have powerline-shell on remote system A and B, and powerline fonts installed locally on MAC. System B looks fine, System A shows the question marks.

Turns out I dnd't have the correct locale settings, can test it with this:

echo -e "\xE2\x98\xA0"

adding the following to /etc/environment fixed for me (log out/back in afterwards)
export LANG=en_US.UTF-8 (or applicable UTF-8 encoding)

**Comment by dulgan** [comment]
I had the same problem, setting Meslo Powerline font as iTerm font solved the problem, thanks @Junus

**Comment by ryanoasis** [comment]
@Janus @dulgan :+1:

I think this can be closed, however maybe a FAQ can start being built to help out. I wasn't able to find anything on the repo regarding UTF-8.

**Comment by webbj74** [comment]
If you're using iTerm2 make sure to change both the **Regular Font** and **Non-ASCII Font** to a powerline font.

**Comment by ryanoasis** [comment]
@webbj74 Nice thanks.

Started a FAQ [here](https://github.com/milkbikis/powerline-shell/wiki/FAQ)

**Comment by drgeb** [comment]
Nice! Thanks As soon as I changed my machine's iTerm2 fonts to a powerline font it worked, as mentioned by webbj74 above!

**Comment by ryanoasis** [comment]
I think this can be closed

**Comment by b-ryan** [comment]
Thanks for the FAQ @ryanoasis - I just added a link to it in the README

**Comment by Foadsf** [comment]
Ok, I had this issue using my macOs terminal sshing to a server. I read here and there that installing  Meslo font would resolve the issue, nobody explaining what it means. Well, from here I learned how it is done:

1. Download the Meslo font from [here](https://github.com/powerline/fonts/blob/master/Meslo%20Slashed/Meslo%20LG%20M%20Regular%20for%20Powerline.ttf) by selecting the `View Raw`
2. install it by just simply opening and clicking on install...
3. Follow [these instructions](https://gist.github.com/kevin-smets/8568070#gistcomment-1350857) to select your terminal's font to Meslo. 

That's it. your problem should be solved now!
