### ISSUE TITLE
Error: traces below the line

### ISSUE THREAD

**Issue by frnogueira** [banga/powerline-shell#226]
How to fix this error?

![error](https://cloud.githubusercontent.com/assets/2768725/12772523/984168a6-ca10-11e5-8464-bbf9487b8391.png)

**Comment by ryanoasis** [comment]
What is the font?

**Comment by frnogueira** [comment]
Cantarell - System font of Arch LInux.

I did Install powerline-fonts... So, Cantarell is not compatible?

**Comment by frnogueira** [comment]
Nothing! Cantarell is not compatible. Roboto Mono sounds good! ;)
