### ISSUE TITLE
pwd not getting updated correctly

### ISSUE THREAD

**Issue by kimusan** [banga/powerline-shell#227]
I have now setup the powerline-shell and at first it looks like it works (at least it changed the design of my bash prompt).
Unfortunately it does not seem to change the path in the prompt for me. If I start in my home-dir it wil show the path to be "~" at all times - even after moving to other directory. 

Any ideas as to what could be wrong here?

Ubuntu 16.04 + bash prompt.

**Comment by kimusan** [comment]
turns out it was the test if[TERM != linux ] that gave me the problem. By removing that it started working. I tested with both gnome-terminal, terminator and the gnome-shell dropdown terminal. They all set it to linux it seems.

**Comment by b-ryan** [comment]
@kimusan do you mean that `$TERM` is `linux` on gnome-terminal, terminator, and gnome-shell? But the `if` statement was causing problems?

**Comment by kimusan** [comment]
at least on my system it seemed that way (will test tomorrow when I am back at the office again)

**Comment by kimusan** [comment]
ok this is strange. 
If I just load my bash prompt in any of the before mentioned terminals, then it does not seem to work. If I then re-source the .bashrc file, then it suddenly works. 
I cannot explain why this is.

**Comment by b-ryan** [comment]
I guess you got this working. There is a big backlog of issues and PRs so I'm going to close this. If you see any more oddities feel free to re-open.

**Comment by zangman** [comment]
I have the same problem, it just started out of the blue and everything was working just fine until today.

Following up on kumusan's comment, it looks like running the following command gets the path updated correctly again:

/usr/local/lib/python2.7/dist-packages/powerline/bindings/bash/powerline.sh

Something changed in my setup that is not causing this script to run at the right time. I'm using tmux so I could just add this in the config as part of the startup, but that seems like the wrong fix.

**Comment by zangman** [comment]
After a lot of digging I was able to fix it by adding `PROMPT_COMMAND=''` in the line before `powerline.sh` is called in my .bashrc file. This seems to be vaguely related to this bug here:

https://github.com/powerline/powerline/issues/727

**Comment by Superdanby** [comment]
@zangman, thank you. I was facing the same issue. And now it works.

> After a lot of digging I was able to fix it by adding `PROMPT_COMMAND=''` in the line before `powerline.sh` is called in my .bashrc file. This seems to be vaguely related to this bug here:
> 
> [powerline/powerline#727](https://github.com/powerline/powerline/issues/727)
