### ISSUE TITLE
Tab auto complete Issues

### ISSUE THREAD

**Issue by lachgil** [banga/powerline-shell#230]
Hello,

First of all I just installed powerline and I'm loving it, works really well and was easy to setup,

I have a big host file and used to use auto complete for ssh and telnet.
SSH works, but telnet doesn't. 

Thanks

**Comment by b-ryan** [comment]
Just due to the age of this issue (sorry :cry: - my fault) I'm going to close it. If you are still out there having this issue, please re-open and we can try to get to the bottom of it.
