### ISSUE TITLE
Sometimes PowerLine doesn't show up

### ISSUE THREAD

**Issue by yvgny** [banga/powerline-shell#236]
Hi !
Sometimes when I open the terminal PowerShell doesn't show up and I'm stuck with this screen :
<img width="760" alt="plbug" src="https://cloud.githubusercontent.com/assets/1623687/14941817/d5569912-0fa9-11e6-9c3a-386ae82b4a3a.png">

 But I can execute some commands :
<img width="850" alt="plbug" src="https://cloud.githubusercontent.com/assets/1623687/14941840/72c7b26c-0faa-11e6-93d8-f7e146735256.png">

Re-open the terminal doesn't solve the problem, the only way I found to solve this is to restart my computer but I'm sure there's an easier way to fix that.. What can we do about this ?

P.S: This problem happens with fish and bash, so I don't think the problem is related to this...

Thank you !

**Comment by Benxamin** [comment]
Please check the symlink. I had this same issue when I was linking to the **powerline_shell_base.py** file.
`powerline-shell.py@ -> powerline-shell/powerline_shell_base.py`

It should be:
`powerline-shell.py@ -> powerline-shell/powerline-shell.py`

**Comment by MySickDude** [comment]
Thank you for your answer ! In fact, instead of creating a symlink I copied the whole file (**powerline-shell.py**). Is it a bad thing ?
I have to specify that most of the time PowerLine show up and works as expected, but sometimes (I use PowerLine since like 3-4 days and it only produces twice) PowerLine doesn't show up.

**Comment by b-ryan** [comment]
@MySickDude when this happens, can you paste the output of `~/powerline_shell.py` here?

**Comment by geraldarthur** [comment]
hm, i've been having a similar issue for the past month or so where powerline just doesn't show up if i run `install_powerline_precmd` from my `.zshrc`. i was able to fix it a while back by re-cloning the repo, but now even that isn't helping. here's my powerline-shell.py file & system info.

https://gist.github.com/geraldarthur/3021452655ffb4bae09a75ae9c0d569a

os x 10.11.4
<img width="466" alt="screen shot 2016-05-02 at 11 34 36 am" src="https://cloud.githubusercontent.com/assets/1578563/14963737/d9a2c0b2-1059-11e6-8da2-af992adf1a9a.png">

**Comment by MySickDude** [comment]
The problem happened again, so here is the output of ~/powershell-line.py using the "cat" command: http://pastebin.com/a6tuh082

**Comment by b-ryan** [comment]
@MySickDude sorry I should have specified -- not looking for the output using `cat`. Can you instead show the output using `python`? Ie run:

```
python ~/powerline_shell.py`
```

**Comment by MySickDude** [comment]
@b-ryan Oh yes sorry it was pretty obvious... Here is the output : 

> Traceback (most recent call last):
  File "/Users/sachakozma/powerline-shell.py", line 650, in <module>
    add_fossil_segment(powerline)
  File "/Users/sachakozma/powerline-shell.py", line 643, in add_fossil_segment
    _add_fossil_segment(powerline)
  File "/Users/sachakozma/powerline-shell.py", line 613, in _add_fossil_segment
    subprocess.Popen(['fossil'], stdout=subprocess.PIPE).communicate()[0]
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1334, in _execute_child
    child_exception = pickle.loads(data)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pickle.py", line 1382, in loads
    return Unpickler(file).load()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pickle.py", line 858, in load
    dispatch[key](self)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pickle.py", line 966, in load_string
    raise ValueError, "insecure string pickle"
ValueError: insecure string pickle

**Comment by b-ryan** [comment]
Looks like this might be the issue: https://bugs.python.org/issue26083

In any case, powerline should:

1. Have a better way to diagnose errors. I didn't realize the README instructs user to redirect stderr to `/dev/null`. I don't do this personally, so I'm able to see exceptions when they happen.
2. Catch all exceptions when adding a particular segment and warn the user.

**Comment by MySickDude** [comment]
@b-ryan Thank you for your help ! So I just have to apply the patch provided to solve the problem ?

**Comment by b-ryan** [comment]
@MySickDude I hope that's all you have to do, but I don't know for sure.

**Comment by MySickDude** [comment]
@b-ryan Thank you, I will try this ! Thank you for all the help :-)

**Comment by Datamance** [comment]
@MySickDude did applying the patch work?

**Comment by Vkt0r** [comment]
Getting the last version for Python 2.7 in https://www.python.org/getit/ works very well for me after reset the terminal

**Comment by b-ryan** [comment]
Based on above discussion it sounds like there is a Python bug that people may have been running into. I also finally changed the installation instructions to not redirect stderr (as I mentioned in https://github.com/banga/powerline-shell/issues/236#issuecomment-217874840). Following the new instructions will cause any exceptions to be printed, helping people diagnose issues.
