### ISSUE TITLE
The root name indication doesn't turn red

### ISSUE THREAD

**Issue by incapable** [banga/powerline-shell#238]
On debian(jessie) systems the name "root" turns red at the beginning of the line.
When i tried it on my fedora(23) system, it just stays gray like any other users.

Images:
[imgur](http://imgur.com/a/gSApo)

**Comment by Ikkerens** [comment]
Experiencing a similar issue myself, also on Fedora.

**Comment by b-ryan** [comment]
I would assume this has been fixed by: https://github.com/banga/powerline-shell/pull/175 which I just released. You will have to use the latest setup instructions for powerline-shell and make sure to be using version 0.3.1. If this doesn't resolve the issue feel free to re-open.
