### ISSUE TITLE
Prompt Issues

### ISSUE THREAD

**Issue by ExiaHan** [banga/powerline-shell#243]
Hi, i am using Archlinux, i found there may be a prompt display issue wile build AOSP(Android Source Code). This is the step that may reproduct the issue:
- have a aosp branch copy in local machine  ( in my scenario it's android-6.0.1_r30)
- execute "source ./build/envsetup.sh" to set up the build env
- execute "lunch 1" to select a target that will be build
  Then the prompt issue may occur, the directory which is displayed by prompt will never be changed after change to other directory via "cd".

**Comment by steven-jackson** [comment]
I had the same problem and it finally became annoying enough for me to figure out. This isn't the fault of powerline, it's caused by envsetup.sh overwriting PROMPT_COMMAND, you can disable it by making STAY_OFF_MY_LAWN non-empty.
