### ISSUE TITLE
Git Prompt doesn't show

### ISSUE THREAD

**Issue by ryanbaldwin** [banga/powerline-shell#250]
I'm banging my head here, and can't figure out what's wrong... I have fish/powerline-shell installed on my laptop and it's fine. But on my iMac it just simply doesn't work.

Basically, here's the issue:
If I'm _not_ in a git repo then the powerline-shell prompt shows up in all its glory. However, as soon as I cd into a git repo, it just totally disappears.

See screenshot for example
![screen shot 2016-09-22 at 9 34 31 pm](https://cloud.githubusercontent.com/assets/955086/18771368/643eba28-810c-11e6-9e6f-97b2f8ee9faf.png)

**Comment by ryanbaldwin** [comment]
update: I did the following from the python REPL:

>>> add_git_segment(_)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "git.py", line 73, in add_git_segment
    stats = parse_git_stats(status)
  File "git.py", line 43, in parse_git_stats
    stats = RepoStats()
NameError: global name 'RepoStats' is not defined
>>> 

So I'm guessing that's the main issue?

**Comment by b-ryan** [comment]
That error is a tad misleading. I think there was some other exception being thrown, but being suppressed. The latest version of this project includes new installation instructions, one of which will cause any exceptions to be shown. I would love to know if that helps you figure out what's wrong.
