### ISSUE TITLE
A Pypi package

### ISSUE THREAD

**Issue by azmeuk** [banga/powerline-shell#254]
Hi. Congratulations for this prompt, I use it everywhere.
It would be nice to have a pip package containing it. What do you think?

Thanks again

**Comment by b-ryan** [comment]
I would love to do this. But I think it's a long way from happening. The project is not well set up for it at the moment. The `install.py` script is what actually generates the executable. I would prefer to try to move to a model where this project works like any other python library. There are performance implications with that though.

For now I'm just going to have to close this and keep the idea on the backburner.
