### ISSUE TITLE
Bug: print "(detached)" outside of git repository instead of nothing

### ISSUE THREAD

**Issue by matthieuxyz** [banga/powerline-shell#270]
in powerline-shell.py line 383 there is this code:
```python
    if 'Not a git repo' in err:
        return
```
Which check the error message _in english_ to determine if the current directory is a git repository or not. 

Well, git isn't always in english. The error message on my system is 

> fatal:
> Ni ceci ni aucun de ses répertoires parents (jusqu'au point de montage /home) n'est un dépôt git
> Arrêt à la limite du système de fichiers (GIT_DISCOVERY_ACROSS_FILESYSTEM n'est pas activé).

So the test fail and powerline-shell print (detached) instead of nothing.

Fix:

The command "git symbolic-ref -q HEAD" has an exit status 128 when the current directory is not a git repository, maybe we can check that instead.

**Comment by MCMic** [comment]
I have the same problem.
An other easy fix is to use locale C like it’s done for other commands:
    p = subprocess.Popen(['git', 'symbolic-ref', '-q', 'HEAD'],
            env={"LANG": "C"}, stdout=subprocess.PIPE, stderr=subprocess.PIPE)

**Comment by MCMic** [comment]
Hum, my bad this was because I did not refresh powerline-shell.py by doing ./install.py, this is already fixed in master, I think you can close this issue.

**Comment by matthieuxyz** [comment]
I can confirm that running install.py is enough to fix this issue. Thanks @MCMic .

Closing the issue.
