### ISSUE TITLE
exit code segment has never worked for me

### ISSUE THREAD

**Issue by shikhanshu** [banga/powerline-shell#277]
I have never seen the prompt change color when last command had non zero exit code. I have enabled the segment in config always. Do I need to do something more?

**Comment by b-ryan** [comment]
The other thing necessary is to make sure your prompt is configured correctly. See https://github.com/banga/powerline-shell#bash

If you are using bash or zsh, the important part is the `$?`.

**Comment by shikhanshu** [comment]
The prompt is rendered by powerline-shell, right! I am not defining the
prompt myself at all.
Yes I know about $?, but where do I verify that "it is configured
correctly" ?


Thanks,
Shikhanshu

**Comment by shikhanshu** [comment]
Oh, so $? should be the first argument to powerline-shell.py? Ok, I will
try that out.


Thanks,
Shikhanshu

**Comment by shikhanshu** [comment]
Nope, that made no difference whatsoever.

**Comment by b-ryan** [comment]
Could you let me know:

- Your operating system
- What shell you are using (bash/zsh/fish)
- Did you make sure to `source` your `.bashrc` after making the `$?` change?

**Comment by shikhanshu** [comment]
> SUSE11SP4
> tcsh
> This is what my .cshrc.local contains (and yes, I logged out and logged
back in after the change):
    set prompt = "`~/bin/powerline-shell.py $? --shell tcsh
--colorize-hostname`"
    alias cd 'cd \!*; set prompt = "`~/bin/powerline-shell.py $? --shell
tcsh --colorize-hostname`"'

Please don't laugh at my OS and shell :) This is a work machine and I don't
have any say over the image.
That said, everything works except the return code colorization, so I am ok!



Thanks,
Shikhanshu

**Comment by b-ryan** [comment]
Haha, no judgment here. It looks like for tcsh you should replace `$?` with `$status`.

**Comment by b-ryan** [comment]
Ah ok. Yes you should have a `$` on the end of your shell and it will turn red. Like: 
![selection_006](https://user-images.githubusercontent.com/1183997/29281749-39fcfd28-80ee-11e7-8a9a-25a61ff7d880.png)

This is the code that is dealing with this: 
https://github.com/banga/powerline-shell/blob/master/segments/root.py

I think the issue is that you are passing `--shell tsch` - there is no support for tsch. I don't know much about tsch but I would recommend passing `bash` as the argument instead.

**Comment by shikhanshu** [comment]
I have modified my generated powerline-shell.py to add tcsh support:
def add_root_segment(powerline):
    root_indicators = {
        'bash': ' \\$ ',
        'zsh': ' %# ',
        'bare': ' $ ',
        'tcsh': ' \\$ '
    }

But I don't see the root segment getting colored.

Anyway, I don't want to waste more of your time on this :) Thanks for your
help!


Thanks,
Shikhanshu

**Comment by shikhanshu** [comment]
Come to think of it - the prompt is set once. And then changed only when I
cd into some other directory. So it makes sense that exit code from
previous command is not going to make a difference. Perhaps it is a tcsh
limitation that prompt is not re-computed every time a command is run?


Thanks,
Shikhanshu

**Comment by b-ryan** [comment]
Oh I totally missed your comment above about how you have configured tcsh:

```
 set prompt = "`~/bin/powerline-shell.py $? --shell tcsh --colorize-hostname`"
alias cd 'cd \!*; set prompt = "`~/bin/powerline-shell.py $? --shell tcsh --colorize-hostname`"'
```

Yeah this won't work because you are only ever recomputing the prompt when you `cd`. I don't know whether there is a way to get tcsh to re-compute the prompt every command. Unfortunately I am not much help there.
