### ISSUE TITLE
Improper escaping of command substitutions

### ISSUE THREAD

**Issue by justjanne** [banga/powerline-shell#279]
Steps to reproduce:

1. ```mkdir -p /tmp/\~/\$HOME/\`uptime\`/\$\(uname\)/```
2. ```cd /tmp/\~/\$HOME/\`uptime\`/\$\(uname\)/```

Expected results:

``` kuschku  discovery  tmp  ~  $HOME  `uptime`  $(uname)  $  ```

Actual results:

``` kuschku  discovery  tmp  ~  /home/kuschku   21:54:23 up  8:57,  5 users,  load average: 0.66, 0.77, 0.81  Linux  %  ```

**Comment by b-ryan** [comment]
This is being discussed in https://github.com/banga/powerline-shell/pull/264 - thanks!
