### ISSUE TITLE
Takes a long time to source .zshrc

### ISSUE THREAD

**Issue by twhite96** [banga/powerline-shell#281]
OS: macOS 10.12.6
Zsh Shell

I followed the tutorial and added the powerline function to my `.zshrc` file but it takes a long time to source, which I need to quit out of and comment out the function in my `.zshrc` file, source the file again to get my terminal back to working correctly.

Any idea as to what is going on?

**Comment by b-ryan** [comment]
Hi @twhite96 - are you sure it is taking a long time or could powerline-shell just be failing entirely?

**Comment by twhite96** [comment]
@b-ryan it was user error. Didn't symlink the powerline python script to my home directory correctly. **But**. My terminal froze completely when having this enabled. I couldn't exit out of it. I had to force quit, remove the powerline function from my `.zshrc` file, and reboot. Don't know why that happened. I have disabled it for now.

**Comment by b-ryan** [comment]
Ok - sorry you had issues. Let me know if I can help any further.
