### ISSUE TITLE
Does not work with fish-shell?

### ISSUE THREAD

**Issue by jD91mZM2** [banga/powerline-shell#290]
No escape sequences are correctly printed out. `echo -ne (powerline-shell --shell bare)` does not work very well either.

**Comment by ELChris414** [comment]
Can confirm

**Comment by b-ryan** [comment]
Can confirm as well - sorry about this. I did a major overhaul recently. Will fix asap.

**Comment by jD91mZM2** [comment]
Hey, no problem! I've been using an old version of this for a while, and I gotta say it's the best powerline alternative out there. All of you people working on it did a great job :smile:

**Comment by b-ryan** [comment]
Just released the fix. You can get the latest version using:

```
pip install --upgrade powerline-shell
```

This should install version 0.2.1. Please let me know if you have any further issues.

**Comment by b-ryan** [comment]
Well thanks!

**Comment by jD91mZM2** [comment]
Woah, that was insanely fast! Thank you!

**Comment by ELChris414** [comment]
INSANE You are an amazing dev, thanks!

**Comment by b-ryan** [comment]
aw shucks :)
