### ISSUE TITLE
Support tcsh?

### ISSUE THREAD

**Issue by shikhanshu** [banga/powerline-shell#299]
My workplace uses tcsh (no way getting around that). Can you PLEASE support tcsh?
In the previous iterations of powerline-shell (before it became a pypi module), I was able to manually edit powerline-shell.py and all was well.

But it would be great to be able to not have to change anything manually.

Compared to bash, the difference is just this:
```
        'tcsh': '%%{\\e%s%%}'
        'bash': '\\[\\e%s\\]',

```

**Comment by b-ryan** [comment]
@shikhanshu see https://github.com/banga/powerline-shell/pull/301 let me know if you spot any issues.
