### ISSUE TITLE
ornamental question mark looks weird

### ISSUE THREAD

**Issue by nschloe** [banga/powerline-shell#300]
Git, as opposed to all other VCSs, uses a question mark instead of a plus sign to indicate files which aren't checked in. Not sure why this is, but I'm sure there's an explanation (which could perhaps be added to the README.md).

Anyhow, for the question mark, powerline-shell does _not_ use `?` but [`\u2753`](http://www.fileformat.info/info/unicode/char/2753/index.htm), the 'BLACK QUESTION MARK ORNAMENT':

![q](https://user-images.githubusercontent.com/181628/31235737-8918700e-a9f2-11e7-9c90-366070daee7b.png)

At first, I thought my font was broken. Why not use the actual question mark `?` (or a `+` for that matter)?

**Comment by b-ryan** [comment]
> Git, as opposed to all other VCSs

This is mostly not true as of the last version. I think the only holdout is the `hg` segment, but in the next release, it too will match the way `git` behaves.

> Why not use the actual question mark

That I don't know. I added the functionality to `git` years ago and used `+` at the time. Somewhere along the line it was switched to what you see today. I don't really see any reason to use that over a regular question mark, so I think we should just switch to that.

**Comment by shikhanshu** [comment]
So the conclusion here is that regular '?' will be used for untracked files in git? That would be perfect.

**Comment by b-ryan** [comment]
@shikhanshu yes.

**Comment by shikhanshu** [comment]
@b-ryan does the latest release contain this fix?

**Comment by b-ryan** [comment]
Ah no it doesn't. I will do this now.

**Comment by shikhanshu** [comment]
@b-ryan thanks!

**Comment by b-ryan** [comment]
Released! It's in version 0.4.2
