### ISSUE TITLE
Unicode character 2753 not rendering

### ISSUE THREAD

**Issue by shikhanshu** [banga/powerline-shell#302]
I have latest patched powerline-shell fonts. All the symbols work fine, except the 'untracked' indicator in git.
The 'untracked' character shows up literally as '\U+2753'. I tried switching to various different powerline fonts but none of them seem to have this character.

Can you fix this character? Or expose the option to change the unicode chars via powerline-shell.json? I think the latter is good to have anyway!

![image](https://user-images.githubusercontent.com/31578/31413918-66f7d096-add0-11e7-85e5-c7e16e8f80d5.png)

**Comment by b-ryan** [comment]
Going to close since this is covered in https://github.com/banga/powerline-shell/issues/300
