### ISSUE TITLE
Patched mode doesn't show properly after installing texlive packages (probably fonts)

### ISSUE THREAD

**Issue by cyberalex4life** [banga/powerline-shell#304]
I'm using OpenSUSE Leap 42.3 (GnomeShell 3.20.2) and after installing some texlive package collections, my prompt show's like this:

![patched](https://user-images.githubusercontent.com/2423189/31586272-4d6e6b70-b1d7-11e7-8c6c-3fa491b8210d.jpg)

Compatible mode looks like this:
![compatible](https://user-images.githubusercontent.com/2423189/31586284-83f9b528-b1d7-11e7-937e-d1bb136df362.jpg)

Is there a way to fix it?  I tried powerline-fonts but it doesn't fix the issue.

My Gnome Tweak Tool fonts section looks like this:

![gnom-tweak-tool-fonts-section](https://user-images.githubusercontent.com/2423189/31586313-d7da5260-b1d7-11e7-9d07-29201f709e93.jpg)

My `~/.powerline-shell.json` containes
```
{
  "segments": [
    "virtual_env", 
    "username", 
    "hostname", 
    "ssh", 
    "cwd", 
    "git", 
    "hg", 
    "jobs", 
    "root"
  ],
  "mode": "compatible",
  "cwd": {
    "mode": "plain"
  },
  "theme": "washed"
}
```

**Comment by shikhanshu** [comment]
"I tried powerline-fonts but it doesn't fix the issue."
- Hope you rebuilt font cache and updated gnome configuration to use UTF-8 encoding (if not already), and set a patched font for the terminal?

**Comment by cyberalex4life** [comment]
Sorry mate, I did install your patched fonts, I just didn't know they named 'for powerline'. Your fonts are good enough for me, thanks.

**Comment by b-ryan** [comment]
@cyberalex4life is that to mean you resolved the issue? Sorry if I misunderstood.

**Comment by cyberalex4life** [comment]
Yes, by using a patched font for Monospace.
At first I didn't realize that your patched font titles must include "FOR POWERLINE", so this is why I opened this issue. You can close it now.

**Comment by b-ryan** [comment]
thanks
