### ISSUE TITLE
Command not found ( power-shell )

### ISSUE THREAD

**Issue by FLY1NN** [banga/powerline-shell#306]
Hello, I just did a clean install of Arch and have been attempting to install powerline-shell onto my system with little success. I am running the latest version of Arch with zsh as the terminal. I have attempted to install several times, all of which have resulted in the error below. 

![powerline-shell](https://user-images.githubusercontent.com/30763844/31596346-e60b7d22-b20f-11e7-95c8-cf45ed239ff7.png)

Any help in resolving this issue would be much appreciated. 
Thanks!

**Comment by sambadevi** [comment]
Same issue on ubuntu bash on windows 10, after running `pip install powerline-shell` and adding the necessary setup to .bashrc I get `powerline-shell: Command not found`

**Comment by sambadevi** [comment]
Never mind installing it with git clone and sudo seemed to fix the problem on my side

**Comment by jD91mZM2** [comment]
```
export PATH="$PATH:$HOME/.local/bin"
```

**Comment by b-ryan** [comment]
@FLY1NN I would try the suggestion from @jD91mZM2 or try to install globally with 

```
pip install powerline-shell
```

If installing with `--user` is causing this issue I'm going to change the default suggested installation method.

**Comment by sambadevi** [comment]
@b-ryan when I re-installed the tool I omitted the user switch as well. Maybe it helps in general

**Comment by jD91mZM2** [comment]
It helps because it installs it in a different location, which is added into the .profile by default

**Comment by FLY1NN** [comment]
Thanks for all the suggestions, I will try these out tonight.

**Comment by FLY1NN** [comment]
You guys are amazing! I completely uninstalled powerline-shell and then reinstalled using
`pip install powerline-shell`
without `--user` and it worked like a charm!

**Comment by b-ryan** [comment]
I just updated the README to remove `--user` as the recommended install method.
