### ISSUE TITLE
Is this supposed to happen?

### ISSUE THREAD

**Issue by jD91mZM2** [banga/powerline-shell#307]
I just got the latest version today, and I have no idea what's going on: ![Screenshot](https://i.imgur.com/g89VhWx.png)

**Comment by b-ryan** [comment]
Interesting. Are you using zsh? Do you have a custom config file at `~/.powerline-shell` or are you using the default?

**Comment by jD91mZM2** [comment]
Hmm... Was just about to say I tried downgrading and it's the same thing.

I'm using Fish Shell.  
I have removed two segments from `~/.powerline-shell`.  
This must be related to my recent switch to Arch Linux I suppose...

**Comment by jD91mZM2** [comment]
Ugh, so sorry for the title spam. Accidentally pressed enter

**Comment by b-ryan** [comment]
Could you post your entire `~/.powerline-shell.json` here so I can try the same config on my end?

**Comment by jD91mZM2** [comment]
Ah, sure!

```
{
  "segments": [
    "virtual_env",
    "ssh",
    "cwd",
    "git",
    "hg",
    "jobs",
    "root"
  ]
}
```

**Comment by b-ryan** [comment]
No luck reproducing on my end. What version of fish are you using?

**Comment by jD91mZM2** [comment]
I'm using fish version 2.6.0 and bash version 4.4.12(1)-release. I'll see if I can reproduce it in a VM.

**Comment by tbodt** [comment]
Bug is not correctly handling the case when `$HOME` has a trailing slash.

**Comment by jD91mZM2** [comment]
UPDATE: I'm midway in reinstalling arch in a VM, messed with partitions and all that. Took a while. Then my friend who knows literally everything (@tbodt) comes along in a group chat and says "Hey, print $HOME". **It has a trailing slash.** So `/home/jD91mZM2` doesn't match. And `/home/jD91mZM2/Downloads` becomes `~Downloads`.

**Comment by b-ryan** [comment]
Oh man - nice. Thanks @tbodt 

I can attempt to fix later, but if you want to make a PR I will be happy to look

**Comment by tbodt** [comment]
#309

**Comment by b-ryan** [comment]
Just released that fix. It doesn't seem to me like it's going to fix the weird spacing issue though.

**Comment by tbodt** [comment]
That might be a separate issue, I don't know.

**Comment by jD91mZM2** [comment]
The spacing issue was fixed. I have no idea why it was caused (plus, it only appeared in Fish), but if it works it works :stuck_out_tongue:

**Comment by minils** [comment]
A bit late but maybe still helpful...

The following solved the issue for me:
`sudo dnf install langpacks-en glibc-all-langpacks -y`
You probably need to install `langpacks-XX` for your language as well.

(I'm on Fedora 30)
