### ISSUE TITLE
not able to remove uninstall powerline-shell

### ISSUE THREAD

**Issue by arunsingh** [banga/powerline-shell#325]
I installed the powerline-shell, Now I want to remove it, not able to remove it, or what settings I need to do to get normal default bash shell. Kindly point out the issue to get back to normalcy.
![bash_powerline-shell](https://user-images.githubusercontent.com/1364776/32597210-dd2ab176-c4ea-11e7-94c7-6320330f5935.png)

**Comment by b-ryan** [comment]
Hi @arunsingh - you just have to undo the changes described here: https://github.com/banga/powerline-shell#bash - ie. remove that code from your bashrc

**Comment by arunsingh** [comment]
thanks , it got resolved as you marked.
