### ISSUE TITLE
Indentation problem while going to a new line in fish

### ISSUE THREAD

**Issue by hashinclude** [banga/powerline-shell#88]
When I write the following 
![screenshot from 2013-08-29 08 09 22](https://f.cloud.github.com/assets/1989695/1047034/4ee74608-1054-11e3-84b3-5acfd207e22b.png)

and press enter, it indents all lines one block right. 
![screenshot from 2013-08-29 08 09 38](https://f.cloud.github.com/assets/1989695/1047033/4eb0f634-1054-11e3-866f-28012ab11f37.png)

**Comment by b-ryan** [comment]
I also just tried this with fish and didn't have the issue.
